-- MySQL Script generated by MySQL Workbench
-- 09/09/19 14:44:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema produccion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema produccion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `produccion` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `produccion` ;

-- -----------------------------------------------------
-- Table `produccion`.`pro_procesos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`pro_procesos` (
`id_proceso` INT NOT NULL AUTO_INCREMENT,
`nombre` VARCHAR(60) NOT NULL,
`fecha_inicio` DATE NULL,
`fecha_finalizacion` DATE NULL,
`icono` VARCHAR(45) NOT NULL,
`descripcion` TEXT NULL,
PRIMARY KEY (`id_proceso`),
UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`sys_empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`sys_empleados` (
`id_empleado` INT NOT NULL AUTO_INCREMENT,
`nombre` VARCHAR(45) NOT NULL,
`paterno` VARCHAR(45) NOT NULL,
`materno` VARCHAR(45) NOT NULL,
`genero` VARCHAR(45) NULL,
`fecha_nacimiento` VARCHAR(45) NULL,
`telefono` VARCHAR(45) NULL,
`cargo` VARCHAR(45) NULL,
PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_clientes` (
`id_cliente` INT NOT NULL AUTO_INCREMENT,
`nombre` VARCHAR(45) NOT NULL,
`telefono` VARCHAR(45) NOT NULL,
`nit_ci` VARCHAR(45) NULL,
`razon_social` VARCHAR(45) NULL,
`direccion` VARCHAR(45) NULL,
PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`ven_orden_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`ven_orden_pedidos` (
`id_orden_pedido` INT NOT NULL AUTO_INCREMENT,
`cliente_id` INT NOT NULL,
`nro_pedido` VARCHAR(45) NOT NULL,
`tipo_pedido` ENUM('estandar','especial') NOT NULL,
`fecha_pedido` DATETIME NOT NULL,
`fecha_entrega` DATETIME NOT NULL,
`archivo` VARCHAR(45) NULL,
`requerimiento` TEXT NULL,
`observacion` TEXT NULL,
PRIMARY KEY (`id_orden_pedido`),
INDEX `fk_ven_orden_pedidos_inv_clientes1_idx` (`cliente_id` ASC),
UNIQUE INDEX `nro_pedido_UNIQUE` (`nro_pedido` ASC),
CONSTRAINT `fk_ven_orden_pedidos_inv_clientes1`
FOREIGN KEY (`cliente_id`)
REFERENCES `produccion`.`inv_clientes` (`id_cliente`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`pro_orden_producciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`pro_orden_producciones` (
`id_orden_produccion` INT NOT NULL AUTO_INCREMENT,
`orden_pedido_id` INT NOT NULL,
`nro_produccion` INT NOT NULL,
`fecha_produccion` DATETIME NOT NULL,
`fecha_inicio` DATETIME NULL,
`fecha_entrega` DATETIME NULL,
`estado` ENUM('planificado','liberado') NOT NULL,
PRIMARY KEY (`id_orden_produccion`),
INDEX `fk_pro_orden_producciones_ven_orden_pedidos1_idx` (`orden_pedido_id` ASC),
UNIQUE INDEX `nro_produccion_UNIQUE` (`nro_produccion` ASC),
CONSTRAINT `fk_pro_orden_producciones_ven_orden_pedidos1`
FOREIGN KEY (`orden_pedido_id`)
REFERENCES `produccion`.`ven_orden_pedidos` (`id_orden_pedido`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_almacenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_almacenes` (
`id_almacen` INT NOT NULL AUTO_INCREMENT,
`almacen` VARCHAR(45) NOT NULL,
`direccion` VARCHAR(45) NOT NULL,
`telefono` VARCHAR(45) NOT NULL,
`descripcion` VARCHAR(45) NOT NULL,
`principal` VARCHAR(45) NOT NULL,
PRIMARY KEY (`id_almacen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_ingresos` (
`id_ingreso` INT NOT NULL AUTO_INCREMENT,
`almacen_id` INT NOT NULL,
`fecha_ingreso` VARCHAR(45) NOT NULL,
`hora_ingreso` VARCHAR(45) NOT NULL,
`tipo` ENUM('compra','traspaso','producido') NOT NULL,
`descripcion` VARCHAR(45) NOT NULL,
`monto_total` VARCHAR(45) NOT NULL,
`nombre_proveedor` VARCHAR(45) NOT NULL,
`nro_registros` VARCHAR(45) NOT NULL,
`fecha_vencimiento` DATE NULL,
`nro_lote` VARCHAR(45) NULL,
PRIMARY KEY (`id_ingreso`),
INDEX `fk_inv_ingresos_inv_almacenes_idx` (`almacen_id` ASC),
CONSTRAINT `fk_inv_ingresos_inv_almacenes`
FOREIGN KEY (`almacen_id`)
REFERENCES `produccion`.`inv_almacenes` (`id_almacen`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_egresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_egresos` (
`id_egreso` INT NOT NULL AUTO_INCREMENT,
`almacen_id` INT NOT NULL,
`cliente_id` INT NULL,
`fecha_egreso` VARCHAR(45) NOT NULL,
`hora_egreso` VARCHAR(45) NOT NULL,
`tipo` VARCHAR(45) NOT NULL,
`descripcion` VARCHAR(45) NOT NULL,
`nro_factura` VARCHAR(45) NOT NULL,
`nro_autorizacion` VARCHAR(45) NOT NULL,
`codigo_control` VARCHAR(45) NOT NULL,
`fecha_limite` VARCHAR(45) NOT NULL,
`monto_total` VARCHAR(45) NOT NULL,
`nro_registros` VARCHAR(45) NULL,
`inv_egresoscol` VARCHAR(45) NULL,
PRIMARY KEY (`id_egreso`),
INDEX `fk_inv_egresos_inv_almacenes1_idx` (`almacen_id` ASC),
INDEX `fk_inv_egresos_pro_clientes1_idx` (`cliente_id` ASC),
CONSTRAINT `fk_inv_egresos_inv_almacenes1`
FOREIGN KEY (`almacen_id`)
REFERENCES `produccion`.`inv_almacenes` (`id_almacen`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_inv_egresos_pro_clientes1`
FOREIGN KEY (`cliente_id`)
REFERENCES `produccion`.`inv_clientes` (`id_cliente`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_egresos_detalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_egresos_detalles` (
`id_egreso_detalle` INT NOT NULL AUTO_INCREMENT,
`egreso_id` INT NOT NULL,
`precio` VARCHAR(45) NOT NULL,
`cantidad` VARCHAR(45) NOT NULL,
`descuento` VARCHAR(45) NOT NULL,
`sku` VARCHAR(100) NULL,
PRIMARY KEY (`id_egreso_detalle`),
INDEX `fk_pro_egresos_detalles_inv_egresos1_idx` (`egreso_id` ASC),
CONSTRAINT `fk_pro_egresos_detalles_inv_egresos1`
FOREIGN KEY (`egreso_id`)
REFERENCES `produccion`.`inv_egresos` (`id_egreso`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_categorias` (
`id_categoria` INT NOT NULL AUTO_INCREMENT,
`categoria` VARCHAR(45) NOT NULL,
`descripcion` TEXT NULL,
PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_productos` (
`id_producto` INT NOT NULL AUTO_INCREMENT,
`categoria_id` INT NOT NULL,
`nombre` VARCHAR(45) NOT NULL,
`nombre_factura` VARCHAR(45) NOT NULL,
`fecha_registro` DATE NOT NULL,
`hora_registro` TIME NOT NULL,
`descripcion` TEXT NOT NULL,
PRIMARY KEY (`id_producto`),
INDEX `fk_inv_productos_inv_categorias1_idx` (`categoria_id` ASC),
CONSTRAINT `fk_inv_productos_inv_categorias1`
FOREIGN KEY (`categoria_id`)
REFERENCES `produccion`.`inv_categorias` (`id_categoria`)
ON DELETE CASCADE
ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_producto_atributos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_producto_atributos` (
`id_producto_atributo` INT NOT NULL AUTO_INCREMENT,
`producto_id` INT NOT NULL,
`codigo_barras` VARCHAR(50) NULL,
`sku` VARCHAR(50) NULL,
`cantidad_minima` INT NOT NULL,
`imagen` VARCHAR(45) NULL,
`tipo` ENUM('producto','material') NOT NULL,
INDEX `fk_inv_producto_atributo_inv_productos1_idx` (`producto_id` ASC),
PRIMARY KEY (`id_producto_atributo`),
UNIQUE INDEX `sku_UNIQUE` (`sku` ASC),
UNIQUE INDEX `codigo_barras_UNIQUE` (`codigo_barras` ASC),
CONSTRAINT `fk_inv_producto_atributo_inv_productos1`
FOREIGN KEY (`producto_id`)
REFERENCES `produccion`.`inv_productos` (`id_producto`)
ON DELETE CASCADE
ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_ingresos_detalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_ingresos_detalles` (
`id_ingreso_detalle` INT NOT NULL AUTO_INCREMENT,
`producto_atributo_id` INT NOT NULL,
`ingreso_id` INT NOT NULL,
`cantidad` DECIMAL(10,2) NOT NULL,
`costo` VARCHAR(45) NULL,
PRIMARY KEY (`id_ingreso_detalle`),
INDEX `fk_inv_ingresos_detalles_inv_ingresos1_idx` (`ingreso_id` ASC),
INDEX `fk_inv_ingresos_detalles_inv_producto_atributos1_idx` (`producto_atributo_id` ASC),
CONSTRAINT `fk_inv_ingresos_detalles_inv_ingresos1`
FOREIGN KEY (`ingreso_id`)
REFERENCES `produccion`.`inv_ingresos` (`id_ingreso`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_inv_ingresos_detalles_inv_producto_atributos1`
FOREIGN KEY (`producto_atributo_id`)
REFERENCES `produccion`.`inv_producto_atributos` (`id_producto_atributo`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`sys_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`sys_users` (
`id_user` INT NOT NULL AUTO_INCREMENT,
`username` VARCHAR(45) NOT NULL,
`password` VARCHAR(45) NOT NULL,
`email` VARCHAR(45) NOT NULL,
`avatar` VARCHAR(45) NOT NULL,
`active` VARCHAR(45) NOT NULL,
`login_at` VARCHAR(45) NOT NULL,
`logout_at` VARCHAR(45) NOT NULL,
`permiso` VARCHAR(45) NOT NULL,
`rol_id` INT NOT NULL,
`persona_id` VARCHAR(45) NULL,
`almacen_id` VARCHAR(45) NULL,
PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`sys_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`sys_roles` (
`id_rol` INT NOT NULL AUTO_INCREMENT,
`rol` VARCHAR(45) NOT NULL,
`descripcion` VARCHAR(45) NOT NULL,
PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`sys_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`sys_permisos` (
`id_permiso` INT NOT NULL,
`rol_id` VARCHAR(45) NOT NULL,
`menu_id` VARCHAR(45) NOT NULL,
`archivos` VARCHAR(45) NOT NULL,
PRIMARY KEY (`id_permiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`sys_menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`sys_menus` (
`id_menu` INT NOT NULL AUTO_INCREMENT,
`menu` VARCHAR(45) NOT NULL,
`icono` VARCHAR(45) NOT NULL,
`ruta` VARCHAR(45) NOT NULL,
`modulo` VARCHAR(45) NOT NULL,
`orden` VARCHAR(45) NOT NULL,
`antecesor_id` VARCHAR(45) NOT NULL,
PRIMARY KEY (`id_menu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`sys_instituciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`sys_instituciones` (
`id_institucion` INT NOT NULL AUTO_INCREMENT,
`nombre` VARCHAR(45) NULL,
`sigla` VARCHAR(45) NULL,
`lema` VARCHAR(45) NULL,
`razon_social` VARCHAR(45) NULL,
`propietario` VARCHAR(45) NULL,
`direcion` VARCHAR(45) NULL,
`telefono` VARCHAR(45) NULL,
`nit` VARCHAR(45) NULL,
`correo` VARCHAR(45) NULL,
`imagen_encabezado` VARCHAR(45) NULL,
`pie_pagina` VARCHAR(45) NULL,
`formato` VARCHAR(45) NULL,
PRIMARY KEY (`id_institucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_unidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_unidades` (
`id_unidad` INT NOT NULL,
`unidad` VARCHAR(45) NOT NULL,
`sigla` VARCHAR(45) NOT NULL,
`tamanio` VARCHAR(45) NOT NULL,
`descripcin` VARCHAR(45) NOT NULL,
PRIMARY KEY (`id_unidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_proformas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_proformas` (
`id_proforma` INT NOT NULL AUTO_INCREMENT,
`fecha_proforma` VARCHAR(45) NULL,
`hora_proforma` VARCHAR(45) NULL,
`descripcion` VARCHAR(45) NULL,
`nro_plataforma` VARCHAR(45) NULL,
`monto_total` VARCHAR(45) NULL,
`descuento_porcentaje` VARCHAR(45) NULL,
`descuento_bs` VARCHAR(45) NULL,
`monto_total_descuento` VARCHAR(45) NULL,
`nombre_cliente` VARCHAR(45) NULL,
`nit_ci` VARCHAR(45) NULL,
`telefono` VARCHAR(45) NULL,
`nro_registros` VARCHAR(45) NULL,
`validez` VARCHAR(45) NULL,
`tipo_documento` VARCHAR(45) NULL,
`observacion` VARCHAR(45) NULL,
PRIMARY KEY (`id_proforma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_asignaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_asignaciones` (
`id_asignacion` INT NOT NULL AUTO_INCREMENT,
`producto_atributo_id` INT NOT NULL,
`unidad_id` INT NOT NULL,
`precio_actual` VARCHAR(45) NOT NULL,
`tipo` ENUM('principal','secundario') NOT NULL,
PRIMARY KEY (`id_asignacion`),
INDEX `fk_inv_asignaciones_inv_producto_atributos1_idx` (`producto_atributo_id` ASC),
INDEX `fk_inv_asignaciones_inv_unidades1_idx` (`unidad_id` ASC),
CONSTRAINT `fk_inv_asignaciones_inv_producto_atributos1`
FOREIGN KEY (`producto_atributo_id`)
REFERENCES `produccion`.`inv_producto_atributos` (`id_producto_atributo`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_inv_asignaciones_inv_unidades1`
FOREIGN KEY (`unidad_id`)
REFERENCES `produccion`.`inv_unidades` (`id_unidad`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_precios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_precios` (
`id_precio` INT NOT NULL AUTO_INCREMENT,
`asignacion_id` INT NOT NULL,
`user_id` INT NOT NULL,
`precio` DECIMAL(10,2) NOT NULL,
`fecha_registro` DATE NOT NULL,
`hora_registro` DATETIME NOT NULL,
PRIMARY KEY (`id_precio`),
INDEX `fk_inv_precios_inv_asignaciones1_idx` (`asignacion_id` ASC),
INDEX `fk_inv_precios_sys_users1_idx` (`user_id` ASC),
CONSTRAINT `fk_inv_precios_inv_asignaciones1`
FOREIGN KEY (`asignacion_id`)
REFERENCES `produccion`.`inv_asignaciones` (`id_asignacion`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_inv_precios_sys_users1`
FOREIGN KEY (`user_id`)
REFERENCES `produccion`.`sys_users` (`id_user`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_proformas_detalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_proformas_detalles` (
`id_proforma_detalle` INT NOT NULL AUTO_INCREMENT,
`producto_atributo_id` INT NOT NULL,
`proforma_id` INT NOT NULL,
`precio` DECIMAL(10,2) NULL,
`cantidad` VARCHAR(45) NULL,
`descuento` VARCHAR(45) NULL,
PRIMARY KEY (`id_proforma_detalle`),
INDEX `fk_inv_proformas_detalles_inv_proformas1_idx` (`proforma_id` ASC),
INDEX `fk_inv_proformas_detalles_inv_producto_atributos1_idx` (`producto_atributo_id` ASC),
CONSTRAINT `fk_inv_proformas_detalles_inv_proformas1`
FOREIGN KEY (`proforma_id`)
REFERENCES `produccion`.`inv_proformas` (`id_proforma`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_inv_proformas_detalles_inv_producto_atributos1`
FOREIGN KEY (`producto_atributo_id`)
REFERENCES `produccion`.`inv_producto_atributos` (`id_producto_atributo`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_monedas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_monedas` (
`id_moneda` INT NOT NULL AUTO_INCREMENT,
`moneda` VARCHAR(45) NOT NULL,
`sigla` VARCHAR(45) NOT NULL,
`oficial` VARCHAR(45) NOT NULL,
PRIMARY KEY (`id_moneda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_atributos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_atributos` (
`id_atributo` INT NOT NULL AUTO_INCREMENT,
`atributo` VARCHAR(45) NULL,
PRIMARY KEY (`id_atributo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_valores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_valores` (
`id_valor` INT NOT NULL AUTO_INCREMENT,
`atributo_id` INT NOT NULL,
`valor` VARCHAR(45) NULL,
PRIMARY KEY (`id_valor`),
INDEX `fk_inv_atributos_detalles_inv_atributos1_idx` (`atributo_id` ASC),
CONSTRAINT `fk_inv_atributos_detalles_inv_atributos1`
FOREIGN KEY (`atributo_id`)
REFERENCES `produccion`.`inv_atributos` (`id_atributo`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`pro_orden_detalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`pro_orden_detalles` (
`id_orden_detalle` INT NOT NULL AUTO_INCREMENT,
`orden_produccion_id` INT NOT NULL,
`sku` VARCHAR(45) NOT NULL,
`cantidad` VARCHAR(45) NULL,
PRIMARY KEY (`id_orden_detalle`),
INDEX `fk_pro_orden_detalle_pro_orden_produccion1_idx` (`orden_produccion_id` ASC),
CONSTRAINT `fk_pro_orden_detalle_pro_orden_produccion1`
FOREIGN KEY (`orden_produccion_id`)
REFERENCES `produccion`.`pro_orden_producciones` (`id_orden_produccion`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`pro_tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`pro_tareas` (
`id_tarea` INT NOT NULL AUTO_INCREMENT,
`proceso_id` INT NOT NULL,
`tarea` VARCHAR(45) NOT NULL,
`descripcion` TEXT NOT NULL,
`fecha_inicio` DATETIME NULL,
`fecha_fin` DATETIME NULL,
PRIMARY KEY (`id_tarea`),
INDEX `fk_pro_tareas_pro_procesos1_idx` (`proceso_id` ASC),
UNIQUE INDEX `tarea_UNIQUE` (`tarea` ASC),
CONSTRAINT `fk_pro_tareas_pro_procesos1`
FOREIGN KEY (`proceso_id`)
REFERENCES `produccion`.`pro_procesos` (`id_proceso`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`pro_control_calidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`pro_control_calidad` (
`id_control_calidad` INT NOT NULL AUTO_INCREMENT,
`tarea_id` INT NOT NULL,
`empleado_id` INT NOT NULL,
`observacion` VARCHAR(45) NULL,
`pro_control_calidadcol` VARCHAR(45) NULL,
PRIMARY KEY (`id_control_calidad`),
INDEX `fk_pro_control_calidad_pro_tareas1_idx` (`tarea_id` ASC),
INDEX `fk_pro_control_calidad_sys_empleados1_idx` (`empleado_id` ASC),
CONSTRAINT `fk_pro_control_calidad_pro_tareas1`
FOREIGN KEY (`tarea_id`)
REFERENCES `produccion`.`pro_tareas` (`id_tarea`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_pro_control_calidad_sys_empleados1`
FOREIGN KEY (`empleado_id`)
REFERENCES `produccion`.`sys_empleados` (`id_empleado`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`tmp_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`tmp_productos` (
`id_producto` INT NOT NULL AUTO_INCREMENT,
`nombre` VARCHAR(45) NULL,
`sku` VARCHAR(45) NULL,
PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`pro_formulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`pro_formulas` (
`id_formula` INT NOT NULL AUTO_INCREMENT,
`orden_detalle_id` INT NOT NULL,
`proceso_id` INT NOT NULL,
`tmp_producto_id` INT NOT NULL,
PRIMARY KEY (`id_formula`),
INDEX `fk_inv_formulas_pro_orden_detalle1_idx` (`orden_detalle_id` ASC),
INDEX `fk_inv_formulas_pro_procesos1_idx` (`proceso_id` ASC),
INDEX `fk_pro_formulas_tmp_productos1_idx` (`tmp_producto_id` ASC),
CONSTRAINT `fk_inv_formulas_pro_orden_detalle1`
FOREIGN KEY (`orden_detalle_id`)
REFERENCES `produccion`.`pro_orden_detalles` (`id_orden_detalle`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_inv_formulas_pro_procesos1`
FOREIGN KEY (`proceso_id`)
REFERENCES `produccion`.`pro_procesos` (`id_proceso`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_pro_formulas_tmp_productos1`
FOREIGN KEY (`tmp_producto_id`)
REFERENCES `produccion`.`tmp_productos` (`id_producto`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`pro_maquinarias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`pro_maquinarias` (
`id_maquinarias` INT NOT NULL AUTO_INCREMENT,
`tarea_id` INT NOT NULL,
`marca` VARCHAR(45) NULL,
`fecha_funcionamiento` VARCHAR(45) NULL,
PRIMARY KEY (`id_maquinarias`),
INDEX `fk_pro_maquinarias_pro_tareas1_idx` (`tarea_id` ASC),
CONSTRAINT `fk_pro_maquinarias_pro_tareas1`
FOREIGN KEY (`tarea_id`)
REFERENCES `produccion`.`pro_tareas` (`id_tarea`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`inv_detalle_maquinaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`inv_detalle_maquinaria` (
`idinv_detalle_maquinaria` INT NOT NULL,
`maquinaria_id` VARCHAR(45) NULL,
`operario_id` VARCHAR(45) NULL,
`hora_inicio` VARCHAR(45) NULL,
`hora_final` VARCHAR(45) NULL,
`nro_veces` VARCHAR(45) NULL,
PRIMARY KEY (`idinv_detalle_maquinaria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`pro_formula_partes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`pro_formula_partes` (
`id_formula_parte` INT NOT NULL AUTO_INCREMENT,
`formula_id` INT NOT NULL,
`tmp_producto_id` INT NOT NULL,
PRIMARY KEY (`id_formula_parte`),
INDEX `fk_pro_formula_partes_inv_formulas1_idx` (`formula_id` ASC),
INDEX `fk_pro_formula_partes_tmp_productos1_idx` (`tmp_producto_id` ASC),
CONSTRAINT `fk_pro_formula_partes_inv_formulas1`
FOREIGN KEY (`formula_id`)
REFERENCES `produccion`.`pro_formulas` (`id_formula`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_pro_formula_partes_tmp_productos1`
FOREIGN KEY (`tmp_producto_id`)
REFERENCES `produccion`.`tmp_productos` (`id_producto`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`pro_empleado_tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`pro_empleado_tareas` (
`id_empleado_tarea` INT NOT NULL AUTO_INCREMENT,
`empleado_id` INT NOT NULL,
`tarea_id` INT NOT NULL,
PRIMARY KEY (`id_empleado_tarea`),
INDEX `fk_pro_empleado_tareas_sys_empleados1_idx` (`empleado_id` ASC),
INDEX `fk_pro_empleado_tareas_pro_tareas1_idx` (`tarea_id` ASC),
CONSTRAINT `fk_pro_empleado_tareas_sys_empleados1`
FOREIGN KEY (`empleado_id`)
REFERENCES `produccion`.`sys_empleados` (`id_empleado`)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT `fk_pro_empleado_tareas_pro_tareas1`
FOREIGN KEY (`tarea_id`)
REFERENCES `produccion`.`pro_tareas` (`id_tarea`)
ON DELETE CASCADE
ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`ven_pedido_detalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`ven_pedido_detalles` (
`id_pedido_detalle` INT NOT NULL AUTO_INCREMENT,
`orden_pedido_id` INT NOT NULL,
`producto_atributo_id` INT NOT NULL,
`cantidad` INT NULL,
PRIMARY KEY (`id_pedido_detalle`),
INDEX `fk_ven_detalle_pedidos_ven_orden_pedidos1_idx` (`orden_pedido_id` ASC),
INDEX `fk_ven_detalle_pedidos_inv_producto_atributo1_idx` (`producto_atributo_id` ASC),
CONSTRAINT `fk_ven_detalle_pedidos_ven_orden_pedidos1`
FOREIGN KEY (`orden_pedido_id`)
REFERENCES `produccion`.`ven_orden_pedidos` (`id_orden_pedido`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_ven_detalle_pedidos_inv_producto_atributo1`
FOREIGN KEY (`producto_atributo_id`)
REFERENCES `produccion`.`inv_producto_atributos` (`id_producto_atributo`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produccion`.`pro_materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produccion`.`pro_materiales` (
`producto_id` INT NOT NULL,
`material_id` INT NOT NULL,
`cantidad` DECIMAL(10,2) NOT NULL,
INDEX `fk_pro_materiales_inv_productos1_idx` (`producto_id` ASC),
INDEX `fk_pro_materiales_inv_productos2_idx` (`material_id` ASC),
CONSTRAINT `fk_pro_materiales_inv_productos1`
FOREIGN KEY (`producto_id`)
REFERENCES `produccion`.`inv_productos` (`id_producto`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_pro_materiales_inv_productos2`
FOREIGN KEY (`material_id`)
REFERENCES `produccion`.`inv_productos` (`id_producto`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
